skip_tags: true

image: Visual Studio 2017

clone_depth: 1

branches:
  only:
    - master

install:
  - cinst docfx

build_script:
- dotnet restore
- dotnet build --configuration Release

test_script:
- dotnet test test/DotnetCoreDocfxDemo.UnitTests/DotnetCoreDocfxDemo.UnitTests.csproj --configuration Release

deploy_script:
- bash releaseDocs.sh
